// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBQJuEOi02oL1hvMYYa5S2b2jX28RrFY',
    appId: '1:960054004331:web:0b8a8193e0c1e99030bf2e',
    messagingSenderId: '960054004331',
    projectId: 'snake-game-8b033',
    authDomain: 'snake-game-8b033.firebaseapp.com',
    storageBucket: 'snake-game-8b033.appspot.com',
    measurementId: 'G-HF470VET9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbcO8DNydQNXL90wdr_FoW9HLTyE7KiDM',
    appId: '1:960054004331:android:39f59a7927f4e09230bf2e',
    messagingSenderId: '960054004331',
    projectId: 'snake-game-8b033',
    storageBucket: 'snake-game-8b033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6zcb4Kq8Vqs-kV_vPvyC1YNSFb-BJY-E',
    appId: '1:960054004331:ios:855facf4c365c88630bf2e',
    messagingSenderId: '960054004331',
    projectId: 'snake-game-8b033',
    storageBucket: 'snake-game-8b033.appspot.com',
    iosClientId: '960054004331-ttb51k7kqooecm5gejai4k1pf3psi665.apps.googleusercontent.com',
    iosBundleId: 'com.example.snakeGame',
  );
}
